name: Rust CI

on:
  push:
    branches: [ main ] # run only when merging to main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build examples
      run: cargo build --examples
    - name: Run tests
      run: cargo test --verbose
